depromeet/praise-push-server

- .github/ISSUE_TEMPLATE/issue-template.md
- Resolve: #4 
- Make sure push to the `main` branch to use the issue template.
> docs: Create Github issue template

- .github/ISSUE_TEMPLATE/issue-template.md
> docs: Create issue template

- build.gradle
- src/main/java/com/praise/praisejail/interfaces/adapters/web/swagger/SwaggerConfig.java
> :wrench: Add Swagger config

- src/main/java/com/praise/praisejail/common/error/GlobalExceptionHandler.java
- Resolve: #3 
- Need CustomException and ErrorCode
> :sparkles: feature: Create GlobalException Handler

- src/main/java/com/praise/praisejail/common/ErrorCode.java
> :sparkles: feature: Add ErrorCode

- build.gradle
- src/main/resources/application-dev.yml
- src/main/resources/application-prod.yml
> :sparkles: config: Add application-dev.yml, application-prod.yml

- src/main/java/com/praise/push/user/domain/User.java
- src/main/java/com/praise/push/user/domain/UserAuth.java
- src/main/java/com/praise/push/user/domain/vo/OAuthProvider.java
> :sparkles: feature: Add User Entity

- src/main/java/com/praise/push/comment/domain/Comment.java
- src/main/java/com/praise/push/post/domain/Keyword.java
- src/main/java/com/praise/push/post/domain/Post.java
> :sparkles: add post, keyword, comment entity

- build.gradle
- src/main/resources/application.yml
- Resolve: #32 
기본 profile을 지정하였습니다.
> :sparkles: config: add profile setting

- src/main/java/com/praise/push/comment/domain/Comment.java
- src/main/java/com/praise/push/post/adapter/in/web/PostController.java
- src/main/java/com/praise/push/post/adapter/out/persistence/KeywordJpaEntity.java
- src/main/java/com/praise/push/post/adapter/out/persistence/KeywordMapper.java
- src/main/java/com/praise/push/post/adapter/out/persistence/PostJpaEntity.java
- src/main/java/com/praise/push/post/adapter/out/persistence/PostMapper.java
- src/main/java/com/praise/push/post/adapter/out/persistence/PostPersistenceAdapter.java
- src/main/java/com/praise/push/post/adapter/out/persistence/PostRepository.java
- src/main/java/com/praise/push/post/application/port/in/CreatePostCommand.java
- src/main/java/com/praise/push/post/application/port/in/PostUseCase.java
- src/main/java/com/praise/push/post/application/port/in/UpdatePostCommand.java
- src/main/java/com/praise/push/post/application/port/out/LoadPostPort.java
- src/main/java/com/praise/push/post/application/port/out/PostResponse.java
- src/main/java/com/praise/push/post/application/port/out/RecordPostPort.java
- src/main/java/com/praise/push/post/application/service/PostService.java
- src/main/java/com/praise/push/post/domain/Keyword.java
- src/main/java/com/praise/push/post/domain/Post.java
- Resolve: #36 
**확인 포인트**
- [클린 아키텍처](https://github.com/wikibook/clean-architecture) 만족하였는지 확인 부탁드립니다.
**추후 작업 포인트**
> ✨ feat: postCRUD

- src/main/java/com/praise/push/util/Constants.java
- src/main/java/com/praise/push/util/enums/Constants.java
- Resolve: #51 
정적 변수를 관리할 enum 클래스를 생성했습니다. 
`util/enums` 패키지 안에서 생성해두었으니, 사용하시면 될 것 같습니다~
> Add Enum class 

- .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
> :memo: docs : pull request 템플릿 추가(#55)

- src/main/java/com/praise/push/adapter/in/web/LoginController.java
- src/main/java/com/praise/push/adapter/in/web/UserController.java
- src/main/java/com/praise/push/application/service/KeywordService.java
- src/main/java/com/praise/push/application/service/LoginService.java
- src/main/java/com/praise/push/application/service/UserService.java
- src/main/java/com/praise/push/domain/User.java
> ✨ feature: add nickname change api 

- src/main/java/com/praise/push/adapter/in/web/CommentController.java
- src/main/java/com/praise/push/adapter/in/web/KeywordController.java
- src/main/java/com/praise/push/adapter/in/web/LoginController.java
- src/main/java/com/praise/push/adapter/in/web/PostController.java
- src/main/java/com/praise/push/adapter/in/web/UserController.java
- src/main/java/com/praise/push/application/service/UserService.java
> :sparkles: add swagger annotation

- src/main/java/com/praise/push/adapter/out/persistence/PostPersistenceAdapter.java
- src/main/java/com/praise/push/application/port/out/LoadPostPort.java
- src/main/java/com/praise/push/application/service/PostService.java
- src/main/java/com/praise/push/batch/cron/post/jobs/PostBatchJob.java
- src/main/java/com/praise/push/batch/cron/post/scheduler/PostBatchScheduler.java
- src/main/java/com/praise/push/config/BatchConfig.java
- src/main/java/com/praise/push/domain/Post.java
- src/main/resources/application-local.yml
> :sparkles: add post scheduling

- src/main/resources/application-dev.yml
- src/main/resources/application-prod.yml
> 🔧 config: update application.yml

- src/main/java/com/praise/push/adapter/out/persistence/CommentPersistenceAdapter.java
- src/main/java/com/praise/push/adapter/out/persistence/CommentRepository.java
- src/main/java/com/praise/push/adapter/out/persistence/KeywordPersistenceAdapter.java
- src/main/java/com/praise/push/adapter/out/persistence/PostPersistenceAdapter.java
- src/main/java/com/praise/push/application/port/out/LoadCommentPort.java
- src/main/java/com/praise/push/application/service/CommentService.java
- src/main/java/com/praise/push/common/constant/Constants.java
- src/main/java/com/praise/push/common/error/GlobalExceptionHandler.java
- src/main/java/com/praise/push/common/error/exception/PraiseUpException.java
- src/main/java/com/praise/push/common/error/model/ErrorCode.java
> :sparkles: feature: handle exception

- src/main/java/com/praise/push/domain/User.java
> :sparkles: feature: create user table index

- src/main/java/com/praise/push/application/port/out/LoginResponse.java
- src/main/java/com/praise/push/application/service/UserService.java
- src/main/java/com/praise/push/domain/User.java
> :sparkles: feature: add user entity field

- src/main/java/com/praise/push/application/service/UserService.java
- src/main/java/com/praise/push/domain/User.java
> :sparkles: feature: add random nickname

- src/main/java/com/praise/push/adapter/in/web/PostController.java
Reverts depromeet/praise-push-server#120
> Revert "Fix getPosts controller argument"

- src/main/java/com/praise/push/adapter/out/persistence/PostPersistenceAdapter.java
- src/main/java/com/praise/push/adapter/out/persistence/PostRepository.java
* :ambulance: hotfix: delete title argument(#64)
* :wrench: fix: s3 upload return url bug(#64)
* :sparkles: feature: post pagination(#64)
* :sparkles: feature: post pagination service(#64)
* :sparkles: feature: post load adapter(#64)
- jpql을 활용하여 post와 연관관계에 있는 comment를 조회함
* :recycle: refactor: @Entity annotation designate name value(#64)
* :sparkles: feat: PostSummaryResponseDto(#64)
* :sparkles: feat: apply changed list(#64)
* :sparkles: feat: apply changed list(#64)
* :recycle: refactor: add yml property(#64)
* :recycle: refactor: apply ResponseEntity(#64)
* :sparkles: feat: add isRead variable(#64)
* :recycle: refactor: apply ResponseEntity(#64)
* :sparkles: feature: update post isRead state(#64)
* :recycle: refactor: depart invisible posts from posts(#95)
* :bug: fix: add imageUrl …
> 🚑 Hotfix: add visible parameter (#123)

- src/main/java/com/praise/push/config/SwaggerConfig.java
> Feature: swagger setting https

- src/main/java/com/praise/push/common/error/GlobalExceptionHandler.java
- src/main/java/com/praise/push/common/error/model/ErrorEvent.java
- src/main/java/com/praise/push/common/error/model/ErrorEventListener.java
- src/main/java/com/praise/push/common/monitoring/MonitoringProvider.java
- src/main/java/com/praise/push/common/monitoring/SlackMonitoringProvider.java
- src/main/java/com/praise/push/config/AsyncConfig.java
> :recycle: refactor: add asynchronous to error monitoring

- src/main/java/com/praise/push/adapter/out/persistence/PostPersistenceAdapter.java
- src/main/java/com/praise/push/adapter/out/persistence/PostRepository.java
- src/main/java/com/praise/push/application/port/out/RecordPostPort.java
- src/main/java/com/praise/push/application/service/PostService.java
> :bug: fix: modify post visible open scheduler

- src/main/java/com/praise/push/application/service/PostService.java
- src/main/java/com/praise/push/batch/cron/post/scheduler/PostBatchScheduler.java
- Resolved: #162 
<br>
> 이슈에 작업내용 상세히 기록해두었습니다.
> :recycle: refactor: modify post open scheduler logic

- src/main/java/com/praise/push/adapter/in/web/UserController.java
- src/main/java/com/praise/push/adapter/out/persistence/PostPersistenceAdapter.java
- src/main/java/com/praise/push/adapter/out/persistence/PostRepository.java
- src/main/java/com/praise/push/application/port/in/PostUseCase.java
- src/main/java/com/praise/push/application/port/in/YearMonthCommand.java
- src/main/java/com/praise/push/application/port/in/dto/PostThumbnailResponseDto.java
- src/main/java/com/praise/push/application/port/in/dto/PostYearMonthResponseDto.java
- src/main/java/com/praise/push/application/port/out/LoadPostPort.java
- src/main/java/com/praise/push/application/service/PostService.java
- src/main/java/com/praise/push/batch/cron/post/scheduler/PostBatchScheduler.java
1. **post open 스케쥴러 방식 변경** : 기존 다다음날 자정 -> 변경 후 게시글 작성 시간 기준 30분 후
2. **연도와 월 정보를 받아서 내가 작성한 칭찬 게시글 목록 받아오는 API 구현**
> 🔀 chore: merge develop into main

- src/main/java/com/praise/push/adapter/in/web/PostController.java
- src/main/java/com/praise/push/application/port/out/PostResponseDto.java
* 🐛 Fix: post check logic (#128)
* :ambulance: hotfix: delete title argument(#64)
* :wrench: fix: s3 upload return url bug(#64)
* :sparkles: feature: post pagination(#64)
* :sparkles: feature: post pagination service(#64)
* :sparkles: feature: post load adapter(#64)
- jpql을 활용하여 post와 연관관계에 있는 comment를 조회함
* :recycle: refactor: @Entity annotation designate name value(#64)
* :sparkles: feat: PostSummaryResponseDto(#64)
* :sparkles: feat: apply changed list(#64)
* :sparkles: feat: apply changed list(#64)
* :recycle: refactor: add yml property(#64)
* :recycle: refactor: apply ResponseEntity(#64)
* :sparkles: feat: add isRead variable(#64)
* :recycle: refactor: apply ResponseEntity(#64)
* :sparkles: feature: update post isRead state(#64)
* :recycle: refactor: depart invisible posts from …
> ♻️ Refactor: add postCreatedTime argument (#168)

- src/main/java/com/praise/push/adapter/out/persistence/CommentPersistenceAdapter.java
- src/main/java/com/praise/push/adapter/out/persistence/CommentRepository.java
- src/main/java/com/praise/push/application/port/out/RecordCommentPort.java
- src/main/java/com/praise/push/application/service/UserService.java
- 회원 탈퇴 시 관련된 게시글에 달린 반응들도 모두 삭제
> :bug: fix: add delete related comments (#174)
